import {searchCards,searchSymptoms,resolveCard,resolveSymptom,recordOutcome,OBSERVABLE_AREAS} from './engine.mjs';
const $=id=>document.getElementById(id);
let catalog=null,selected=null,current=null,activeArea=null,pendingPIE=null,issueTitle='',selectedSymptom=null;
const mower={model:'',firmware:''};
// Outcomes stay in memory for this visit; URL/history never contain case or repair data.
const visits=new Map();
const visit=card=>{if(!visits.has(card.id))visits.set(card.id,{completedRepairs:[]});return visits.get(card.id);};
const context=()=>({...visit(selected),...mower});
const navigationSession=crypto.randomUUID();let revision=0,pageName='identify';
const marker=page=>({session:navigationSession,page,revision});
function el(tag,text,className){const n=document.createElement(tag);if(text!==undefined)n.textContent=text;if(className)n.className=className;return n;}
function button(text,action,className='choice'){const n=el('button',text,className);n.type='button';n.addEventListener('click',action);return n;}
function status(text,error=false){$('status').textContent=text;$('status').classList.toggle('error',error);}
function focusResult(){const target=pageName==='solution'?$('solution-page'):$('selection');target.focus({preventScroll:true});target.scrollIntoView({block:'start',behavior:'instant'});}
function clearResult(){$('result').replaceChildren();}
function note(title,lines){const box=el('div',undefined,'alert');box.append(el('h3',title));const list=el('ul');for(const line of lines)list.append(el('li',line));box.append(list);return box;}
function showIdentify(){pageName='identify';$('identify-page').hidden=false;$('solution-page').hidden=true;clearResult();$('solution-summary').replaceChildren();$('status').textContent='Confirm the issue, then continue.';}
function invalidate(){revision++;current=null;showIdentify();history.replaceState(marker('identify'),'','#identify');}
function clearSelection(){selected=null;pendingPIE=null;selectedSymptom=null;issueTitle='';$('selection').replaceChildren();}
function editIssue(){if(pageName==='solution'&&history.state?.session===navigationSession){history.back();}else{showIdentify();history.replaceState(marker('identify'),'','#identify');}}
function backHome(){invalidate();clearSelection();$('search').focus();}
function safePIE(title='Other issue',result){invalidate();selected=null;selectedSymptom=null;issueTitle=title;pendingPIE=result||{action:['Contact PIE with the exact model, observed symptom and any checks or repairs already tried.']};renderIdentification();focusResult();}
function chooseArea(area,restore=false){if(!catalog)return;if(!restore){invalidate();clearSelection();$('search').value='';}activeArea=area;document.querySelectorAll('[data-area]').forEach(n=>n.setAttribute('aria-pressed',String(n.dataset.area===area)));const box=$('symptoms');box.replaceChildren();box.append(el('h3',area+' symptoms'));const list=el('div',undefined,'choices');for(const s of catalog.symptoms.filter(s=>s.observable_area===area)){const b=button(s.label_en,()=>openSymptom(s));b.dataset.symptom=s.symptom_id;b.setAttribute('aria-pressed',String(selectedSymptom===s.symptom_id));list.append(b);}list.append(button('None of these / Other issue',()=>safePIE('Other '+area.toLowerCase()+' issue'),'choice other-choice'));box.append(list);}
function renderAreas(){const descriptions={Movement:'Wheels & motion',Cutting:'Discs & cutting height',Charging:'Charge & station detection',Docking:'Return to station',Power:'Start, battery & shutdown',Positioning:'Location, RTK & maps',Connectivity:'WiFi, mobile & Bluetooth',Sensors:'Bumper & LiDAR',Physical:'Visible damage & water',Software:'Firmware updates'};for(const area of OBSERVABLE_AREAS){const b=button('',()=>chooseArea(area),'area-tile');b.dataset.area=area;b.setAttribute('aria-pressed','false');b.append(el('strong',area),el('span',descriptions[area]));$('areas').append(b);}}
function openSymptom(symptom){if(!catalog)return;invalidate();clearSelection();selectedSymptom=symptom.symptom_id;issueTitle=symptom.label_en;$('search').value='';chooseArea(symptom.observable_area,true);const result=resolveSymptom(catalog,symptom.symptom_id,mower);if(result.kind==='choose_path'){const box=el('article',undefined,'card');box.append(el('h2',issueTitle),el('p','Choose the condition that matches.'));for(const c of result.choices)box.append(button(c.label,()=>openCard(catalog.cards.find(x=>x.id===c.cardId),c.pathId,true)));$('selection').replaceChildren(box);return;}
 const ref=symptom.repair_refs[0],card=ref&&catalog.cards.find(c=>c.id===ref.card_id);if(card)openCard(card,ref.repair_path_id,true);else{pendingPIE=result;renderIdentification();}focusResult();
}
function showSearch(){if(!catalog)return;invalidate();clearSelection();if(activeArea){activeArea=null;$('symptoms').replaceChildren();document.querySelectorAll('[data-area]').forEach(n=>n.setAttribute('aria-pressed','false'));}const result=searchCards(catalog.cards,$('search').value),symptoms=searchSymptoms(catalog.symptoms,$('search').value);
 if(result.kind==='empty'){status('Enter an error code or message.');return;}
 if(result.matches.length===1&&result.kind.startsWith('exact')){openCard(result.matches[0]);return;}
 if(!result.matches.length&&!symptoms.matches.length){safePIE('No guide found for that code or message.',{action:['Keep the exact error code, mower model and what happened. Include any repair already tried.','Contact PIE for the next step. Do not choose a similar code as a replacement instruction.']});return;}
 const box=el('article',undefined,'card');box.append(el('h2','Which message matches?'));const choices=el('div',undefined,'choices');for(const c of result.matches){const b=button('',()=>openCard(c));if(c.code)b.append(el('strong',c.code+' '));b.append(el('span',c.message));choices.append(b);}for(const s of symptoms.matches)choices.append(button(s.label_en,()=>openSymptom(s)));box.append(choices);$('selection').replaceChildren(box);status('Select the exact message or observed symptom.');focusResult();
}
function openCard(card,pathId,fromSymptom=false){invalidate();selected=card;pendingPIE=null;if(!fromSymptom){selectedSymptom=null;issueTitle=card.message;}const state=visit(card);state.qualifierConfirmed=false;state.qualifierRejected=false;if(pathId)state.pathId=pathId;else if(!state.completedRepairs.length&&!state.returned)state.pathId=undefined;renderIdentification();focusResult();}
function resolved(){if(!selected)return pendingPIE?{kind:'escalate',...pendingPIE}:null;const state=visit(selected);return state.qualifierRejected?{kind:'escalate',action:['The observed condition does not match this guide. Contact PIE with the exact model, firmware and what happens during mowing and Functional Test.']}:resolveCard(selected,context());}
// Identification deliberately reads only neutral issue/symptom/qualifier labels.
// No action, part, verification or fallback text is rendered into this page.
function renderIdentification(){const box=el('article',undefined,'card');box.append(el('p','SELECTED ISSUE','eyebrow'),el('h2',issueTitle||selected?.message||'Selected issue'));const result=resolved();if(!result){$('selection').replaceChildren();return;}const state=selected&&visit(selected);
 if(result.kind==='choose_symptom'){box.append(el('h3','What problem do you see?'));const list=el('div',undefined,'choices');for(const c of result.choices)list.append(button(c.symptom,()=>{invalidate();Object.assign(state,{pathId:c.id,qualifierConfirmed:false,qualifierRejected:false});renderIdentification();}));box.append(list);
 }else if(result.kind==='qualifier_required'){box.append(note('Confirm the observed condition',[result.prompt]));for(const c of result.choices)box.append(button(c.label,()=>{invalidate();Object.assign(state,{qualifierConfirmed:c.id==='yes',qualifierRejected:c.id!=='yes'});renderIdentification();}));
 }else{
  const chosen=selected?.paths.find(p=>p.id===state.pathId);if(chosen)box.append(el('p',chosen.symptom,'selected-condition'));
  if(result.kind==='scope_required'){box.append(el('h3','Confirm the mower details'));const details=[];if(selected.scope.models.length)details.push('Guide model: '+selected.scope.models.join(', '));if(selected.scope.firmware.length)details.push('Guide firmware: '+selected.scope.firmware.join(', '));box.append(el('p',details.join(' · '),'hint'),el('p','Update the mower details above, or continue for the next step.'));}
  else box.append(el('p','Selection ready. Continue to view the next step.'));
  const next=button('Continue',viewSolution,'primary');next.id='continue';box.append(next);
  if(selected&&selected.paths.filter(p=>p.directSelectable!==false).length>1)box.append(button('Change symptom',()=>{invalidate();Object.assign(state,{pathId:undefined,qualifierConfirmed:false,qualifierRejected:false});renderIdentification();},'text-button'));
 }
 $('selection').replaceChildren(box);status('Identify the issue before viewing the solution.');
}
function displaySolution(){const result=resolved();if(!result||['choose_symptom','qualifier_required','choose_path'].includes(result.kind)){showIdentify();history.replaceState(marker('identify'),'','#identify');return;}pageName='solution';$('identify-page').hidden=true;$('solution-page').hidden=false;$('solution-summary').replaceChildren(el('p',issueTitle,'issue-summary'),el('p',[mower.model&&mower.model!=='__other__'?mower.model:'Model not confirmed',mower.firmware].filter(Boolean).join(' · '),'hint'));if(selected)renderCard(result);else{clearResult();const box=el('article',undefined,'card');box.append(el('h2',issueTitle),note('Next step with PIE',result.action||['Contact PIE to confirm the next action.']));$('result').append(box);}status('Use the next step for your selected issue.');focusResult();}
function viewSolution(){if(!catalog||!resolved())return;history.replaceState(marker('identify'),'','#identify');history.pushState(marker('solution'),'','#solution');displaySolution();}
function restoreNavigation(){const entry=history.state;if(entry?.session===navigationSession&&entry.revision===revision&&entry.page==='solution'&&location.hash==='#solution')displaySolution();else{showIdentify();history.replaceState(marker('identify'),'','#identify');if(activeArea)chooseArea(activeArea,true);renderIdentification();}}
window.addEventListener('popstate',restoreNavigation);
window.addEventListener('hashchange',()=>{if((pageName==='solution')!==(location.hash==='#solution'))restoreNavigation();});
history.replaceState(marker('identify'),'','#identify');showIdentify();
function renderCard(override){clearResult();const box=el('article',undefined,'card');box.dataset.card=selected.id;const top=el('div',undefined,'card-top');top.append(el('span',selected.code?'ERROR '+selected.code:'SYMPTOM GUIDE','code-label'),button('Edit issue',editIssue,'text-button'));box.append(top,el('h2',selected.message));
 const state=visit(selected);current=override||(state.qualifierRejected?{kind:'escalate',action:['The observed condition does not match this guide. Contact PIE with the exact model, firmware and what happens during mowing and Functional Test.']}:resolveCard(selected,context()));
 if(current.kind==='choose_symptom'){box.append(el('h3','What problem do you see?','choices-title'));const choices=el('div',undefined,'choices');for(const c of current.choices)choices.append(button(c.symptom,()=>{Object.assign(state,{pathId:c.id,qualifierConfirmed:false,qualifierRejected:false});renderCard();}));box.append(choices);
 }else if(current.kind==='reported_fixed'){const success=el('div',undefined,'success');success.append(el('h3','You reported it fixed'),el('p',current.message));box.append(success);
 }else if(current.kind==='qualifier_required'){box.append(note('Confirm the observed condition',[current.prompt]));const choices=el('div',undefined,'choices');for(const c of current.choices)choices.append(button(c.label,()=>{Object.assign(state,{qualifierConfirmed:c.id==='yes',qualifierRejected:c.id!=='yes'});renderCard();}));box.append(choices);
 }else if(['escalate','scope_required'].includes(current.kind)){box.append(note(current.kind==='scope_required'?'Confirm the mower details':'Next step with PIE',current.action||['Contact PIE for the current next step.']));if(current.kind==='scope_required'){const details=[];if(selected.scope.models.length)details.push('Guide model: '+selected.scope.models.join(', '));if(selected.scope.firmware.length)details.push('Guide firmware: '+selected.scope.firmware.join(', '));box.append(el('p',details.join(' · '),'hint'));}
 }else if(['repair','check','information'].includes(current.kind)){const grid=el('div',undefined,'answer-grid');const part=el('section',undefined,'part-box');part.append(el('h3','Most likely faulty part / target area'),el('strong',current.part||(current.kind==='information'?'No repair needed for this message':'Start with the observed condition')));grid.append(part);for(const [heading,items] of [['What to do',current.action],['After repair / verification',current.verification.steps]]){const block=el('section',undefined,'answer-block');block.append(el('h3',heading));const list=el('ol');for(const text of items)list.append(el('li',text));block.append(list);grid.append(block);}const fallback=el('section',undefined,'fallback');fallback.append(el('h3','Still not fixed'),el('p',current.ifNotFixed.message));grid.append(fallback);box.append(grid);
 const outcome=el('div',undefined,'outcome'),label=el('label',undefined,'check-label'),check=el('input');check.type='checkbox';check.id='verification';label.append(check,el('span','I completed the checks above and confirmed the result.'));const buttons=el('div',undefined,'buttons');const act=choice=>{const pathId=current.pathId;const next=recordOutcome(selected,pathId,choice,{...context(),verificationComplete:check.checked});if(next.kind==='verification_required'){status(next.message,true);check.focus();return;}if(choice==='not_fixed')state.completedRepairs=[...new Set([...state.completedRepairs,pathId])];if(choice==='returned')state.returned=true;if(next.pathId)state.pathId=next.pathId;else if(!state.pathId)state.pathId=pathId;if(choice!=='fixed')state.qualifierConfirmed=false;renderCard(next);status(choice==='fixed'?'Result shown for this visit only. No case record was changed.':'Use the next step shown below.');focusResult();};buttons.append(button('Fixed',()=>act('fixed'),'primary'),button('Still not fixed',()=>act('not_fixed'),'secondary'));if(current.kind!=='information')buttons.append(button('The issue returned after repair',()=>act('returned'),'text-button'));outcome.append(label,buttons);box.append(outcome);
 }else box.append(note('Next step with PIE',['Contact PIE to confirm the next action.']));
 if(!['choose_symptom','reported_fixed'].includes(current.kind)&&selected.paths.filter(p=>p.directSelectable!==false).length>1)box.append(button('Change symptom',()=>{Object.assign(state,{pathId:undefined,qualifierConfirmed:false,qualifierRejected:false});editIssue();invalidate();renderIdentification();},'text-button change-symptom'));
 $('result').append(box);
}
function detailsChanged(modelChanged=false){invalidate();mower.model=$('model').value;if(modelChanged)$('firmware').value='';mower.firmware=$('firmware').value.trim();for(const state of visits.values()){state.qualifierConfirmed=false;state.qualifierRejected=false;}renderIdentification();}
$('model').addEventListener('change',()=>detailsChanged(true));$('firmware').addEventListener('input',()=>detailsChanged());$('search').addEventListener('input',()=>{invalidate();clearSelection();});$('search-form').addEventListener('submit',event=>{event.preventDefault();showSearch();});$('edit-issue').addEventListener('click',editIssue);document.querySelectorAll('[data-code]').forEach(b=>b.addEventListener('click',()=>{$('search').value=b.dataset.code;showSearch();}));
const strings=value=>Array.isArray(value)&&value.every(v=>typeof v==='string');
function validCatalog(data){if(data?.schemaVersion!==2||typeof data.knowledgeVersion!=='string'||!Array.isArray(data.cards)||!Array.isArray(data.symptoms))return false;return data.cards.every(c=>typeof c.id==='string'&&(c.code===null||typeof c.code==='string')&&typeof c.message==='string'&&strings(c.aliases)&&strings(c.scope?.models)&&strings(c.scope?.firmware)&&Array.isArray(c.paths)&&c.paths.length&&c.paths.every(p=>typeof p.id==='string'&&typeof p.symptom==='string'&&['repair','check','information','escalate'].includes(p.kind)&&strings(p.action)&&p.action.length&&strings(p.verification?.steps)&&p.verification.steps.length&&typeof p.ifNotFixed?.message==='string'))&&data.symptoms.every(s=>typeof s.symptom_id==='string'&&/^SYM-0(0[1-9]|1[0-9]|2[0-5])$/.test(s.symptom_id)&&OBSERVABLE_AREAS.includes(s.observable_area)&&typeof s.label_en==='string'&&strings(s.aliases)&&Array.isArray(s.repair_refs)&&s.repair_refs.every(r=>data.cards.some(c=>c.id===r.card_id&&c.paths.some(p=>p.id===r.repair_path_id))));}
try{const response=await fetch('./knowledge.json',{cache:'no-store'});if(!response.ok)throw new Error('Guide load failed');const data=await response.json();if(!validCatalog(data))throw new Error('Invalid guide data');catalog=data;for(const model of [...new Set(data.cards.flatMap(c=>c.scope.models))].sort())$('model').append(new Option(model,model));$('model').append(new Option('Other model','__other__'));$('model').disabled=false;$('firmware').disabled=false;$('search-button').disabled=false;document.querySelectorAll('[data-code]').forEach(b=>b.disabled=false);renderAreas();status('Choose a symptom or search the exact code or message.');}catch{catalog=null;status('Guides could not load. Restart the local pilot, or contact PIE for help.',true);}
