import { useEffect, useRef, useState } from "react";

type Case = { id:string; ticket:string; todo:boolean; notes:string; humanGuidance:string; guidanceDirty?:boolean; nff:boolean; nffDirty?:boolean; issueOwner:string; issueOwnerDirty?:boolean; analysisCurrent?:boolean; prepared?:any; analysis?:any; translated?:any; customerZh?:string; replyZh?:string; language:"ZH"|"ORIGINAL"; loading?:string; error?:string; diagnostic?:string; freshnessBlocked?:boolean; phase?:"LOADING"|"ANALYZING"|"READY"|"WAITING"|"INSUFFICIENT"|"STALE"|"ERROR"; generations:Record<string,number> };
const api = async (path:string, body:object) => (await fetch(`/api${path}`, { method:"POST", headers:{"Content-Type":"application/json"}, body:JSON.stringify(body) })).json();
const fresh = ():Case => ({ id:crypto.randomUUID(), ticket:"", todo:false, notes:"", humanGuidance:"", nff:false, issueOwner:"", language:"ORIGINAL", generations:{} });

export function App() {
  const [cases,setCases] = useState<Case[]>([fresh()]);
  const [active,setActive] = useState(0);
  const [tokenOpen,setTokenOpen] = useState(false); const [previewOpen,setPreviewOpen] = useState(false); const [previewPrepared,setPreviewPrepared] = useState<any>(); const [logiqMessage,setLogiqMessage] = useState(""); const [curl,setCurl] = useState(""); const [tokenMessage,setTokenMessage] = useState(""); const [authConfigured,setAuthConfigured] = useState<boolean|undefined>();
  const casesRef = useRef(cases); casesRef.current = cases;
  const current = cases[active];
  useEffect(()=>{ api("/auth/nextop/status",{}).then(value=>setAuthConfigured(Boolean(value.configured))).catch(()=>setAuthConfigured(false)); },[]);
  const patch = (id:string, data:Partial<Case>) => setCases(items => items.map(item => item.id === id ? {...item,...data} : item));
  const live = (id:string, operation:string, generation:number) => casesRef.current.some(item => item.id === id && item.generations[operation] === generation);
  const run = async (item:Case, operation:string, loading:string, action:()=>Promise<any>, apply:(result:any)=>Partial<Case>) => {
    const generation = (item.generations[operation] || 0) + 1;
    const phase=operation==="prepare"?"LOADING":operation==="analyze"?"ANALYZING":undefined;
    setCases(items => items.map(value => value.id === item.id ? {...value, generations:{...value.generations,[operation]:generation}, loading, error:undefined, diagnostic:undefined, ...(phase?{phase}: {})} : value));
    try { const result = await action(); if (live(item.id,operation,generation)) patch(item.id,apply(result)); }
    catch { if (live(item.id,operation,generation)) patch(item.id,{loading:undefined,error:"Local API operation failed."}); }
  };
  const translateCached = async (id:string, kind:"customer"|"reply", text:string) => { const existing=casesRef.current.find(item=>item.id===id); const operation=`${kind}-translation`, generation=((existing?.generations[operation])||0)+1; patch(id,{generations:{...(existing?.generations||{}),[operation]:generation}}); try { const result=await api("/cases/translate-text",{text}); if(!result.success||!result.text)throw new Error("translation"); if(live(id,operation,generation))patch(id,kind==="customer"?{customerZh:String(result.text)}:{replyZh:String(result.text)}); } catch { if(live(id,operation,generation))patch(id,{error:"Chinese translation failed."}); } };
  const analyze = (item=current, guided=false) => item.prepared && item.prepared.latest_sender_role!=="PIE" && run(item,"analyze","Analyzing...",() => api("/cases/analyze",{prepared:item.prepared,human_guidance:item.humanGuidance}), result => { if(!result.success)return {loading:undefined,error:result.message||"Analysis failed.",analysisCurrent:false,phase:"ERROR"}; const analysis=result.analysis; const next:Partial<Case>={prepared:result.prepared,analysis,translated:undefined,customerZh:undefined,replyZh:undefined,language:"ORIGINAL",guidanceDirty:false,analysisCurrent:true,loading:analysis.reply_generation_error||"Ready for review",phase:analysis.information_status==="insufficient"?"INSUFFICIENT":"READY"}; queueMicrotask(()=>{if(analysis.customer_description)translateCached(item.id,"customer",analysis.customer_description);if(analysis.reply_en)translateCached(item.id,"reply",analysis.reply_en);}); return next; });
  const refresh = () => current.prepared && run(current,"refresh","Refreshing...",() => api("/cases/refresh",{prepared:current.prepared}), result => { if(!result.success){if(String(result.error_type||"").startsWith("NEXTOP_AUTH"))setAuthConfigured(false);return {loading:undefined,error:`${result.message||"Latest Nextop state could not be verified."} Showing last successfully loaded snapshot.`,freshnessBlocked:true,analysisCurrent:false,phase:"STALE"};} if(result.requires_reanalyze)queueMicrotask(()=>analyze({...current,prepared:result.prepared,analysisCurrent:false})); const waiting=result.change_type==="NEW_PIE_MESSAGE"; if(waiting&&result.prepared?.fields?.Description)queueMicrotask(()=>translateCached(current.id,"customer",result.prepared.fields.Description)); return {prepared:result.prepared,analysis:waiting?undefined:current.analysis,translated:waiting?undefined:current.translated,customerZh:undefined,replyZh:undefined,loading:result.message,freshnessBlocked:false,analysisCurrent:waiting||result.requires_reanalyze?false:current.analysisCurrent,phase:result.requires_reanalyze?"ANALYZING":waiting?"WAITING":current.phase||"READY"}; });
  const load = () => run(current,"prepare","Loading case...",() => api("/cases/prepare",{source:"nextop",ticket_no:current.ticket}), result => {
    if (!result.success) { const diagnostic=`${result.message || "Case could not be loaded."}\n\nStage: ${result.stage || "unknown"}\nError code: ${result.error_type || "unknown"}${result.detail ? `\nSafe detail: ${result.detail}` : ""}\n\nNo credentials are shown here.`; return {prepared:undefined,analysis:undefined,translated:undefined,customerZh:undefined,replyZh:undefined,loading:undefined,error:result.message || "Case could not be loaded.",diagnostic,freshnessBlocked:true,phase:"ERROR"}; }
    const preparedCase = {...current,prepared:result.prepared,humanGuidance:"",guidanceDirty:false};
    if(result.prepared.latest_sender_role!=="PIE")queueMicrotask(() => analyze(preparedCase));
    else if(result.prepared.fields?.Description)queueMicrotask(() => translateCached(current.id,"customer",result.prepared.fields.Description));
    return {prepared:result.prepared,analysis:undefined,translated:undefined,customerZh:undefined,replyZh:undefined,humanGuidance:"",guidanceDirty:false,analysisCurrent:result.prepared.latest_sender_role==="PIE",nff:current.nffDirty?current.nff:Boolean(result.prepared.existing_case?.nff),issueOwner:current.issueOwnerDirty?current.issueOwner:(current.issueOwner||result.prepared.existing_case?.issue_owner||""),loading:result.prepared.latest_sender_role==="PIE"?"Waiting for agent reply.":"Building context and analyzing...",freshnessBlocked:false,phase:result.prepared.latest_sender_role==="PIE"?"WAITING":"ANALYZING"};
  });
  const translateText = (kind:"customer"|"reply") => { if(kind==="customer"&&current.customerZh){patch(current.id,{customerZh:undefined});return;} if(kind==="reply"&&current.replyZh){patch(current.id,{replyZh:undefined});return;} const text=kind==="customer"?current.analysis?.customer_description:current.analysis?.reply_en; if(text)translateCached(current.id,kind,text); };
  const preparePreview = () => { if(current.guidanceDirty||(!current.analysisCurrent&&current.phase!=="WAITING")){patch(current.id,{error:"Regenerate the current analysis before preparing ITR.",freshnessBlocked:true,phase:"STALE"});return;} return current.prepared && run(current,"preview","Checking latest Nextop state...",() => api("/cases/preview",{prepared:current.prepared}), result => { if(!result.success)return {loading:undefined,error:result.message||"ITR Commit is blocked until the latest Nextop state can be verified.",freshnessBlocked:true,analysisCurrent:false,phase:"STALE"}; setPreviewPrepared(result.prepared); queueMicrotask(()=>setPreviewOpen(true)); return {prepared:current.prepared,loading:result.message,freshnessBlocked:false,phase:current.phase||"READY"}; }); };
  const commit = (prepared=current.prepared) => prepared && current.phase!=="WAITING" && run(current,"commit","Checking latest Nextop state...",async()=>{const latest=await api("/cases/preview",{prepared});if(!latest.success)return latest;return api("/cases/commit",{prepared:latest.prepared,include_itr_todo:current.todo,todo_dirty:true,nff_value:current.nff,nff_dirty:Boolean(current.nffDirty),issue_owner_value:current.issueOwner,issue_owner_dirty:Boolean(current.issueOwnerDirty)});}, result => result.success?{loading:"ITR Commit complete.",freshnessBlocked:false}:{prepared:result.prepared||current.prepared,loading:undefined,error:result.message||"Ticket has changed since ITR preparation. Please review the latest messages.",freshnessBlocked:true});
  const close = (id:string) => setCases(items => { const index=items.findIndex(item=>item.id===id), next=items.filter(item=>item.id!==id); if(active===index)setActive(Math.min(index,Math.max(0,next.length-1))); else if(index<active)setActive(active-1); return next.length ? next : [fresh()]; });
  const review = current.language === "ZH" && current.translated ? current.translated : current.analysis;
  const logiqSupported = current.analysis?.capability?.logiq === "supported";
  const openLogiq = () => { const device=current.prepared?.fields?.["Device name"] || current.prepared?.fields?.device_name; if(!logiqSupported){setLogiqMessage(current.analysis?.capability?.logiq === "unknown" ? "LogiQ is unavailable until product capability is confirmed." : "LogiQ is unsupported for this model.");return;} if(!device){setLogiqMessage("No device name is available to copy.");return;} navigator.clipboard.writeText(device).then(()=>setLogiqMessage("Device name copied. Opening LogiQ…")).catch(()=>setLogiqMessage("Device name could not be copied. Please copy it manually.")); window.open("https://logiq.cloud-cn.mammotion.com/","_blank"); };
  return <main>
    <header><div className="tabs">{cases.map((item,index)=><span className={`tab ${index===active?"active":""}`} key={item.id}><button onClick={()=>setActive(index)}>{item.ticket || "New Case"}{item.phase&&<small className={`tab-state ${item.phase.toLowerCase()}`}>{item.phase}</small>}</button><button className="tab-close" aria-label={`Close ${item.ticket||"case"}`} onClick={()=>close(item.id)}>×</button></span>)}<button onClick={()=>{setCases(items=>[...items,fresh()]);setActive(cases.length);}}>+</button></div><button className={authConfigured?"auth-ok":"auth-required"} onClick={()=>setTokenOpen(true)}>{authConfigured?"Nextop ✓":"Nextop Auth Required"}</button></header>
    <section className="status">{current.loading || current.error || "Ready"}{current.diagnostic&&<details className="diagnostic" open><summary>Help diagnose this failure</summary><pre>{current.diagnostic}</pre><button onClick={()=>navigator.clipboard.writeText(current.diagnostic || "")}>Copy diagnostic</button></details>}</section>
    <div className="workbench"><aside><h2>Context</h2><label>Ticket<input value={current.ticket} onChange={event=>patch(current.id,{ticket:event.target.value})} onKeyDown={event=>event.key==="Enter"&&load()}/></label><button onClick={load}>Search / Load</button>{current.prepared&&<><p>Reference: {current.prepared.ticket_no}</p><label className="todo"><input type="checkbox" checked={current.todo} onChange={event=>patch(current.id,{todo:event.target.checked})}/> Add to ITR Todo</label><textarea placeholder="Session notes" value={current.notes} onChange={event=>patch(current.id,{notes:event.target.value})}/></>}</aside>
    <article><div className="tools"><h1>Case Review</h1><button disabled={!current.prepared} onClick={refresh}>Refresh Latest</button><button disabled={!current.prepared || current.phase==="WAITING"} onClick={()=>analyze()}>Re-analyze</button><button className="logiq" disabled={!logiqSupported} title={logiqSupported ? "Copies device name and opens LogiQ" : "LogiQ is unavailable for this capability"} onClick={openLogiq}>LogiQ · Logs</button></div>{logiqMessage&&<p className="logiq-message">{logiqMessage}</p>}{current.prepared&&!logiqSupported&&<p className="logiq-message">{current.analysis?.capability?.logiq === "unknown" ? "LogiQ is unavailable until product capability is confirmed." : "LogiQ is unsupported for this model."}</p>}
    {current.prepared&&<BasicInfo prepared={current.prepared}/>}
    {current.analysis ? <Review value={current.analysis} customerZh={current.customerZh} onCustomerZh={()=>translateText("customer")}/> : <p className="empty">Load a case to automatically build context and analyze it.</p>}
    {current.prepared&&<section className="guidance"><h3>Human Guidance / 人工回复建议</h3><textarea value={current.humanGuidance} placeholder="输入你的判断或希望回复给代理的处理建议。" onChange={event=>patch(current.id,{humanGuidance:event.target.value,guidanceDirty:true,analysisCurrent:false,generations:{...current.generations,analyze:(current.generations.analyze||0)+1}})}/>{current.guidanceDirty&&<p>Guidance changed · regenerate required</p>}<button disabled={!current.humanGuidance.trim() || current.phase==="WAITING"} onClick={()=>analyze(current,true)}>根据建议重新生成</button></section>}
    <section className="reply"><h3>Email Reply</h3>{current.phase==="WAITING"?<p>Waiting for agent reply.</p>:current.analysis?.reply_generation_error?<p className="reply-error">{current.analysis.reply_generation_error}</p>:<pre>{current.analysis?.reply_en || "—"}</pre>}{current.phase!=="WAITING"&&current.analysis?.reply_en&&<><button onClick={()=>navigator.clipboard.writeText(current.analysis.reply_en)}>Copy Reply</button><button onClick={()=>translateText("reply")}>{current.replyZh?"英文":"中文"}</button>{current.replyZh&&<pre className="translation">{current.replyZh}</pre>}</>}</section>
    {current.prepared&&<span className="result-select"><label><input type="checkbox" checked={current.nff} onChange={event=>patch(current.id,{nff:event.target.checked,nffDirty:true})}/> 加入 NFF</label><label>问题归属<select value={current.issueOwner} onChange={event=>patch(current.id,{issueOwner:event.target.value,issueOwnerDirty:true})}><option value="">未选择</option><option value="产品问题">产品问题</option><option value="代理问题">代理问题</option></select></label></span>}
    <button className="commit" disabled={!current.prepared || current.freshnessBlocked || current.guidanceDirty || !current.analysisCurrent} onClick={preparePreview}>{current.prepared?.can_update?"Update ITR":"Create in ITR"}</button></article></div>
  {previewOpen&&<div className="token-modal"><section className="preview-modal"><h2>{previewPrepared?.can_update?"Update ITR":"Create ITR"} Preview</h2><p>Review the exact fields that will be submitted. Latest Nextop state was checked before this preview.</p><PreviewFields prepared={previewPrepared} todo={current.todo} nff={current.nff} issueOwner={current.issueOwner}/>{current.phase==="WAITING"&&<p className="classification-warning">Commit is unavailable while waiting for an agent reply.</p>}<button className="commit" disabled={current.phase==="WAITING"} onClick={()=>{setPreviewOpen(false);commit(previewPrepared)}}>Confirm / Commit</button><button onClick={()=>setPreviewOpen(false)}>Back</button></section></div>}
  {tokenOpen&&<div className="token-modal"><section><h2>Update Nextop Token</h2><p>In DevTools Network, right-click the <b>pageOrders</b> request → Copy → <b>Copy as cURL</b>. Paste the complete result here. Do not paste the browser address-bar URL.</p><textarea value={curl} onChange={e=>setCurl(e.target.value)} placeholder="Paste the complete Copy as cURL result, beginning with curl"/><button onClick={async()=>{try{const r=await api("/auth/nextop/update",{curl});setTokenMessage(r.success?"Token configured. Load the current ticket again.":(r.message||"Token was not accepted."));if(r.success)setAuthConfigured(true)}catch{setTokenMessage("The local service could not validate the token. Restart PIE ITR and try again.")}}}>Save & Validate</button><button onClick={()=>setTokenOpen(false)}>Close</button><p>{tokenMessage}</p></section></div>}
  </main>;
}

function PreviewFields({prepared,todo,nff,issueOwner}:{prepared:any;todo:boolean;nff:boolean;issueOwner:string}) { const fields=prepared?.fields||{}, classification=fields._classification; const fixed=["Reference No.","Status","Description","Solutions","一级标签","二级标签","PIE-Comment","Ticket Created Time","Replied Time-First","Replied Time-NEW","Total Replied"]; const rows=[...fixed,...Object.keys(fields).filter(key=>!fixed.includes(key)&&!key.startsWith("_")),"加入NFF","问题归属"]; return <><div className="preview-fields">{rows.map(key=>{const value=key==="加入NFF"?(nff?"Yes":"No"):key==="问题归属"?(issueOwner||prepared?.existing_case?.issue_owner||"—"):fields[key]??(key==="加入ITR待办"?todo:"—");return <div className="preview-row" key={key}><strong>{key}</strong><span>{Array.isArray(value)?value.join("\n"):String(value)}</span></div>})}</div>{classification?.status==="UNRESOLVED"&&<p className="classification-warning">Classification unresolved: {classification.reason}</p>}</>; }

function BasicInfo({prepared}:{prepared:any}) { const info=prepared?.list_info||{}, fields=prepared?.fields||{}, counts=prepared?.attachment_counts||{}, model=prepared?.model_resolution||fields._model_resolution||{}, device=prepared?.device_resolution||fields._device_resolution||{}; const attachments=[counts.image&&`IMG ×${counts.image}`,counts.video&&`VIDEO ×${counts.video}`,counts.file&&`LOG/FILE ×${counts.file}`,counts.other&&`OTHER ×${counts.other}`].filter(Boolean).join(" · "); return <p className="basic-info">Partner: {info.outerName||"unresolved"} · Email: {info.outerAddress||"—"}<br/>Device: {device.status==="DEVICE_CONFLICT"?"DEVICE_CONFLICT":fields["Device name"]||device.device_name||"—"} · Model: {model.status==="MODEL_CONFLICT"?`MODEL_CONFLICT (${model.explicit_model} / ${model.prefix_model})`:fields["Model Type"]||model.model||"UNKNOWN"}{attachments&&<> · Attachments: {attachments}</>}</p>; }

function Review({value,customerZh,onCustomerZh}:{value:any;customerZh?:string;onCustomerZh:()=>void}) {
  const field = (label:string,key:string) => <section><h3>{label}</h3><p>{Array.isArray(value?.[key]) ? value[key].join("\n") : value?.[key] || "—"}</p></section>;
  return <>{value?.information_status === "insufficient" && <section className="insufficient"><h3>信息不足</h3><p>{(value.missing_information || []).join("\n") || "—"}</p><h3>需要原因</h3><p>{(value.reason_for_request || []).join("\n") || "—"}</p></section>}<section><h3>Customer Issue</h3><p>{value.customer_description || "—"}</p><button onClick={onCustomerZh}>{customerZh?"原文":"中文"}</button>{customerZh&&<pre className="translation">{customerZh}</pre>}</section>{field("Repair Action","repair_actions")}{field("Blocker","current_blocker")}{field("PIE Guidance","historical_pie_recommendations")}{field("Next Step","ai_suggested_next_step")}{field("Solution","solution")}</>;
}
