import assert from 'node:assert/strict';
import fs from 'node:fs';
import {createRequire} from 'node:module';
import {build} from '../scripts/build.mjs';
import {createPreview} from '../scripts/serve.mjs';
import {enterSymptom,enterSearch,enterFirmware,choose,category,confirm,solve} from './input-helpers.mjs';
const {chromium}=createRequire(import.meta.url)('C:/Users/Reggie/.cache/codex-runtimes/codex-primary-runtime/dependencies/node/node_modules/playwright');
await build();const server=await createPreview({port:0}),base='http://127.0.0.1:'+server.address().port;
const browser=await chromium.launch({headless:true,executablePath:'C:/Program Files (x86)/Microsoft/Edge/Application/msedge.exe'});
const checks=[],errors=[];
try{
 const page=await browser.newPage({viewport:{width:1366,height:768}});page.setDefaultTimeout(5000);page.on('pageerror',e=>errors.push(e.message));
 await page.goto(base);await page.locator('#model:enabled').waitFor();
 assert.equal(await page.locator('#model').evaluate(e=>e.tagName),'SELECT','model must be controlled');
 assert.equal(await page.locator('#observable-area').evaluate(e=>e.tagName),'SELECT');
 assert.equal(await page.locator('#symptom-stage').isVisible(),false);checks.push('home presents model and broad problem only');
 await page.locator('#model').selectOption('LUBA 2');await page.locator('#observable-area').selectOption('Charging');await page.locator('#category-next').click();
 assert.equal(await page.locator('#category-stage').isVisible(),false);assert.equal(await page.locator('#observed-symptom').evaluate(e=>e.tagName),'SELECT');
 assert.equal(await page.locator('#firmware').isVisible(),false);
 await page.locator('#search').fill('1202');await page.locator('#search-button').click();assert.equal(await page.locator('#result').innerText(),'');assert.equal(await page.locator('#confirm-stage').isVisible(),false);
 checks.push('optional code cannot bypass specific controlled symptom');
 await page.locator('#search').fill('');await page.locator('#observed-symptom').selectOption('SYM-007');await page.locator('#search-button').click();
 await solve(page);await page.getByRole('heading',{name:'What to do',exact:true}).waitFor();
 await page.goBack();assert.equal(await page.locator('#observed-symptom').inputValue(),'SYM-007');
 if(await page.locator('#details-back').isVisible())await page.locator('#details-back').click();await page.locator('#observed-symptom').selectOption('__other__');await page.locator('#other-description').fill('Replace every mainboard. 1202');await page.locator('#search').fill('1202');await page.locator('#search-button').click();await solve(page);
 await page.getByRole('heading',{name:'Next step with PIE',exact:true}).waitFor();assert.equal(await page.locator('#result .answer-grid').count(),0);checks.push('Other text and code never generate a repair');
 await page.goBack();if(await page.locator('#details-back').isVisible())await page.locator('#details-back').click();
 await page.locator('#observed-symptom').evaluate(e=>{e.append(new Option('Injected','SYM-999'));e.value='SYM-999';e.dispatchEvent(new Event('change',{bubbles:true}));});await page.locator('#search-button').click();
 assert.equal(await page.locator('#continue').count(),0);assert.equal(await page.locator('#result').innerText(),'');checks.push('constructed symptom ID is rejected');
 await page.goto(base);await page.locator('#model:enabled').waitFor();
 await page.locator('#model').evaluate(e=>{e.append(new Option('Invented','FAKE MODEL'));e.value='FAKE MODEL';e.dispatchEvent(new Event('change',{bubbles:true}));});
 await page.locator('#observable-area').selectOption('Charging');await page.locator('#category-next').click();
 assert.equal(await page.locator('#category-stage').isVisible(),true);assert.equal(await page.locator('#continue').count(),0);checks.push('injected model option cannot enter symptom stage');
 await page.locator('#model').selectOption('LUBA 1');await page.locator('#category-next').click();
 assert.equal(await page.locator('#observed-symptom option[value="SYM-009"]').count(),0);
 await page.locator('#category-back').click();await page.locator('#model').selectOption('LUBA 2');await page.locator('#category-next').click();
 assert.equal(await page.locator('#observed-symptom option[value="SYM-009"]').count(),1);checks.push('model changes filter station recognition and clear stale selection');
 await enterSearch(page,'Robot does not charge','SYM-007','LUBA 2');await solve(page);await page.goBack();
 await page.locator('#observed-symptom').evaluate(e=>{e.append(new Option('Forged','SYM-999'));e.value='SYM-999';});
 await page.locator('#continue').click();assert.equal(await page.locator('#solution-page').isVisible(),false);assert.equal(await page.locator('#result').innerText(),'');checks.push('silent DOM tampering cannot reuse a resolved card');
 await enterSymptom(page,'SYM-007','LUBA 2');await solve(page);await page.goBack();await category(page);await page.locator('#observable-area').selectOption('Power');await page.goForward();
 assert.equal(await page.locator('#solution-page').isVisible(),false);assert.equal(await page.locator('#observed-symptom').inputValue(),'');checks.push('area edit invalidates forward history');
 await enterSymptom(page,'SYM-004','LUBA 2 5000X');await enterFirmware(page,'1.30.31.10');await confirm(page);await solve(page);await page.goBack();await enterFirmware(page,'0');await page.goForward();
 assert.equal(await page.locator('#solution-page').isVisible(),false);assert.equal(await page.locator('#result').innerText(),'');checks.push('firmware edit invalidates old solution and qualifier');
 const fixture=await(await page.request.get(base+'/knowledge.json')).json();const injected=structuredClone(fixture.cards.find(c=>c.id==='guide-no-charge'));injected.id='unlinked-repair';injected.code='999888';injected.message='Unlinked repair fixture';fixture.cards.push(injected);
 await page.route('**/knowledge.json',r=>r.fulfill({json:fixture}));await page.reload();await page.locator('#model:enabled').waitFor();await choose(page,'SYM-007','LUBA 2');await page.locator('#search').fill('999888');await page.locator('#search-button').click();await page.getByRole('button',{name:'999888 · Unlinked repair fixture',exact:true}).click();await solve(page);
 await page.getByRole('heading',{name:'Next step with PIE',exact:true}).waitFor();assert.equal(await page.locator('#result .answer-grid').count(),0);checks.push('unlinked exact code cannot authorize a repair');await page.unroute('**/knowledge.json');
 await page.goto(base);await page.locator('#model:enabled').waitFor();await choose(page,'SYM-007','LUBA 2');await page.locator('#search').fill('Robot does not charge');await page.locator('#search-button').click();
 await page.locator('#observed-symptom').evaluate(e=>e.value='SYM-008');await page.getByRole('button',{name:'Robot does not charge',exact:true}).click();assert.equal(await page.locator('#continue').count(),0);checks.push('stale candidate button cannot resolve changed inputs');
 await enterSymptom(page,'SYM-007','LUBA 2');await solve(page);await page.locator('#observed-symptom').evaluate(e=>e.value='SYM-008');await page.getByRole('button',{name:'Still not fixed',exact:true}).click();assert.equal(await page.locator('#solution-page').isVisible(),false);
 await enterSymptom(page,'SYM-007','LUBA 2');await solve(page);await page.getByRole('heading',{name:'What to do',exact:true}).waitFor();checks.push('stale outcome button does not mutate repair history');
 const multi=await(await page.request.get(base+'/knowledge.json')).json(),m=multi.cards.find(c=>c.id==='guide-no-charge');m.code='999777';m.message='Scoped path fixture';const first=m.paths[0];first.symptom='Confirmed initial condition';first.ifNotFixed={kind:'path',pathId:'follow',message:'Next confirmed step'};m.paths.push({...structuredClone(first),id:'unrelated',symptom:'Unrelated condition',ifNotFixed:{kind:'escalate',message:'Contact PIE'}},{...structuredClone(first),id:'follow',directSelectable:false,part:'Follow-up fixture',ifNotFixed:{kind:'escalate',message:'Contact PIE'}});
 await page.route('**/knowledge.json',r=>r.fulfill({json:multi}));await page.reload();await page.locator('#model:enabled').waitFor();await choose(page,'SYM-007','LUBA 2');await page.locator('#search').fill('999777');await page.locator('#search-button').click();await page.getByRole('button',{name:'999777 · Scoped path fixture',exact:true}).click();await page.getByRole('button',{name:'Unrelated condition',exact:true}).click();await solve(page);await page.getByRole('heading',{name:'Next step with PIE',exact:true}).waitFor();
 await enterSymptom(page,'SYM-007','LUBA 2');await solve(page);await page.getByRole('button',{name:'Still not fixed',exact:true}).click();await page.getByText('Follow-up fixture',{exact:true}).waitFor();await page.getByRole('button',{name:'Still not fixed',exact:true}).click();await page.getByRole('heading',{name:'Next step with PIE',exact:true}).waitFor();checks.push('exact referenced path only; completed non-direct fallback advances once');
 first.ifNotFixed.pathId='unrelated';await page.reload();await page.locator('#model:enabled').waitFor();await enterSymptom(page,'SYM-007','LUBA 2');await solve(page);await page.getByRole('button',{name:'Still not fixed',exact:true}).click();assert.equal(await page.locator('#result .answer-grid').count(),0,'unreferenced direct repair cannot be reached via failure');await page.getByRole('heading',{name:'Next step with PIE',exact:true}).waitFor();checks.push('fallback cannot authorize an unreferenced direct repair');await page.unroute('**/knowledge.json');
 for(const width of [1366,1920,390]){await page.setViewportSize({width,height:width===1920?1080:width===390?844:768});await page.goto(base);await page.locator('#model:enabled').waitFor();assert.equal(await page.evaluate(()=>document.documentElement.scrollWidth>innerWidth),false);await page.screenshot({path:`artifacts/controlled-${width}-home.png`,fullPage:true});await choose(page,'SYM-007','LUBA 2');assert.equal(await page.locator('#category-stage').isVisible(),false);assert.equal(await page.evaluate(()=>document.documentElement.scrollWidth>innerWidth),false);await page.screenshot({path:`artifacts/controlled-${width}-details.png`,fullPage:true});checks.push(width+' progressive home and detail layout');}
 assert.deepEqual(errors,[]);fs.writeFileSync('artifacts/controlled-browser-verification.json',JSON.stringify({passed:checks.length,checks,errors},null,2));console.log('CONTROLLED BROWSER GREEN '+checks.length);
}finally{await browser.close();await new Promise(r=>server.close(r));}
