import fs from 'node:fs';
import path from 'node:path';
import assert from 'node:assert/strict';
import {createRequire} from 'node:module';
import {fileURLToPath} from 'node:url';
import {build} from '../scripts/build.mjs';
import {createPreview} from '../scripts/serve.mjs';
const require=createRequire(import.meta.url);
const {chromium}=require(process.env.PLAYWRIGHT_MODULE||'C:/Users/Reggie/.cache/codex-runtimes/codex-primary-runtime/dependencies/node/node_modules/playwright');
const root=path.resolve(path.dirname(fileURLToPath(import.meta.url)),'..');
await build();
const server=await createPreview({port:0}),base='http://127.0.0.1:'+server.address().port;
const browser=await chromium.launch({headless:true,executablePath:process.env.PILOT_BROWSER||'C:/Program Files (x86)/Microsoft/Edge/Application/msedge.exe'});
const checks=[],errors=[],external=[];
const run=async(name,fn)=>{await fn();checks.push(name);console.log('PASS '+name);};
async function fresh(size={width:1366,height:768},suffix=''){const context=await browser.newContext({viewport:size});const page=await context.newPage();page.setDefaultTimeout(5000);page.on('pageerror',e=>errors.push(e.message));page.on('request',r=>{if(!r.url().startsWith(base)&&!r.url().startsWith('data:'))external.push(r.url());});await page.goto(base+suffix);await page.locator('#search-button:enabled').waitFor();return {page,context};}
async function identify(page){await page.locator('#identify-page:visible').waitFor();assert.equal(await page.locator('#result').innerText(),'');assert.equal(await page.locator('#identify-page .answer-grid,#identify-page #verification').count(),0);assert.doesNotMatch(await page.locator('#identify-page').innerText(),/Most likely faulty part|What to do|After repair|Replace fixture|1\.30\.29\.19|Upper Shell Adapter Cable|Cutting control software/);}
async function solve(page){await identify(page);await page.locator('#continue').click();await page.locator('#solution-page:visible').waitFor();assert.equal(await page.locator('#identify-page').isVisible(),false);}
async function search(page,q){if(await page.locator('#solution-page').isVisible())await page.locator('#edit-issue').click();await page.locator('#search').fill(q);await page.locator('#search').press('Enter');}
async function scope(page){await page.locator('#model').selectOption('LUBA 2 5000X');await page.locator('#firmware').fill('1.30.31.10');}
async function symptom(page,id,area='Cutting'){await page.locator(`[data-area="${area}"]`).click();await page.locator(`[data-symptom="${id}"]`).click();if(id==='SYM-004')await page.getByRole('button',{name:'Fails only in Functional Test; works normally during mowing',exact:true}).click();}
async function pie(page){await page.getByRole('heading',{name:'Next step with PIE',exact:true}).waitFor();assert.equal(await page.locator('#result .answer-grid').count(),0);}
try{
 for(const size of [{width:1366,height:768},{width:1920,height:1080},{width:390,height:844}]){
  const {page,context}=await fresh(size);
  await run(size.width+' identify-only home and safe PIE candidate',async()=>{await identify(page);assert.equal(await page.locator('[data-area]').count(),10);await page.screenshot({path:path.join(root,'artifacts',`two-page-${size.width}-identify.png`),fullPage:true});await symptom(page,'SYM-008','Charging');await solve(page);await pie(page);});
  await run(size.width+' exact code frozen1202 and browser Back selection',async()=>{await search(page,'1202');await page.getByRole('button',{name:'Both cutting discs are free, but the error remains',exact:true}).click();await solve(page);await pie(page);await page.goBack();await identify(page);assert.equal(await page.locator('#search').inputValue(),'1202');assert.match(await page.locator('#selection').innerText(),/Both cutting discs are free/);await solve(page);await pie(page);});
  await run(size.width+' exact message information with verified local Fixed',async()=>{await search(page,'Stereo self-calibration succeeded and the parameters were restored.');await page.getByRole('button',{name:'The mower works normally; no other fault is present',exact:true}).click();await solve(page);await page.getByText('No repair needed for this message',{exact:true}).waitFor();await page.getByRole('button',{name:'Fixed',exact:true}).click();assert.match(await page.locator('#status').innerText(),/checks.*first/);await page.locator('#verification').check();await page.getByRole('button',{name:'Fixed',exact:true}).click();await page.getByText('You reported it fixed',{exact:true}).waitFor();});
  await run(size.width+' fuzzy and unsupported require explicit Continue',async()=>{await search(page,'port disconnected');await identify(page);await page.getByRole('button',{name:/1500.*Chassis data/}).click();await solve(page);await pie(page);await search(page,'999999');await identify(page);await solve(page);await pie(page);});
  await run(size.width+' symptom qualifier repair and restored exact mower context',async()=>{await page.locator('#edit-issue').click();await scope(page);await symptom(page,'SYM-004');await identify(page);await page.getByRole('button',{name:'Yes, this matches',exact:true}).click();await solve(page);assert.deepEqual(await page.locator('#result .answer-grid h3').allTextContents(),['Most likely faulty part / target area','What to do','After repair / verification','Still not fixed']);await page.getByText('Cutting control software',{exact:true}).waitFor();assert.equal(await page.evaluate(()=>document.documentElement.scrollWidth>innerWidth),false);await page.screenshot({path:path.join(root,'artifacts',`two-page-${size.width}-solution.png`),fullPage:true});await page.goBack();await identify(page);assert.equal(await page.locator('#model').inputValue(),'LUBA 2 5000X');assert.equal(await page.locator('#firmware').inputValue(),'1.30.31.10');assert.equal(await page.locator('[data-area="Cutting"]').getAttribute('aria-pressed'),'true');await solve(page);});
  await run(size.width+' failed repair persists across both entries without loops',async()=>{await page.getByRole('button',{name:'Still not fixed',exact:true}).click();await pie(page);await search(page,'Cutting disc does not spin in Functional Test');await solve(page);await pie(page);await page.locator('#edit-issue').click();await symptom(page,'SYM-004');await solve(page);await pie(page);});
  await context.close();
 }
 await run('model edit invalidates forward solution and requires fresh qualifier',async()=>{const {page,context}=await fresh();await scope(page);await symptom(page,'SYM-004');await page.getByRole('button',{name:'Yes, this matches',exact:true}).click();await solve(page);await page.goBack();await page.locator('#model').selectOption('__other__');await page.goForward();await identify(page);assert.equal(await page.locator('#firmware').inputValue(),'');await scope(page);await page.getByRole('button',{name:'Yes, this matches',exact:true}).waitFor();await identify(page);await context.close();});
 await run('code text and symptom edits invalidate stale forward history',async()=>{const {page,context}=await fresh();await search(page,'5501');await solve(page);await page.goBack();await page.locator('#search').fill('1202');await page.goForward();await identify(page);assert.equal(await page.locator('#continue').count(),0);await page.locator('#search').press('Enter');await page.getByRole('button',{name:'There is debris or a physical blockage',exact:true}).click();await solve(page);await page.goBack();await symptom(page,'SYM-008','Charging');await page.goForward();await identify(page);await solve(page);await pie(page);assert.match(await page.locator('#solution-page').innerText(),/Charging stops before full/);await context.close();});
 await run('refresh and direct solution URL cannot restore solution or qualifier',async()=>{const {page,context}=await fresh();await scope(page);await symptom(page,'SYM-004');await page.getByRole('button',{name:'Yes, this matches',exact:true}).click();await solve(page);await page.reload();await page.locator('#search-button:enabled').waitFor();await identify(page);assert.equal(await page.locator('#continue').count(),0);await page.goto(base+'/#solution');await page.locator('#search-button:enabled').waitFor();await identify(page);await context.close();});
 await run('signed codes, historical firmware and candidate privacy remain separate',async()=>{const {page,context}=await fresh();for(const code of ['-2000303','2000303','1000022']){await search(page,code);await solve(page);await pie(page);const text=await page.locator('#result').innerText();if(code==='2000303')assert.match(text,/fresh log/i);assert.ok(!text.includes('2.3.30.26'));}const payload=await(await page.request.get(base+'/knowledge.json')).text();assert.doesNotMatch(payload,/candidate_refs|REP-[A-Z0-9]+-\d{3}|evidence_state|repeated_use_signal/);for(const url of ['/data/feishu-candidates.json','/data/canonical.json','/lib/candidates.mjs'])assert.equal((await page.request.get(base+url)).status(),404);await context.close();});
 await run('all25 normal symptoms and ten Other escapes stay identify-only before Continue',async()=>{const {page,context}=await fresh();const data=await(await page.request.get(base+'/knowledge.json')).json();for(const s of data.symptoms){await symptom(page,s.symptom_id,s.observable_area);await identify(page);}assert.equal(data.symptoms.length,25);for(const area of new Set(data.symptoms.map(s=>s.observable_area))){await page.locator('[data-area="'+area+'"]').click();await page.getByRole('button',{name:'None of these / Other issue',exact:true}).click();await solve(page);await pie(page);await page.locator('#edit-issue').click();}assert.equal(await page.locator('[data-symptom="SYM-026"],[data-symptom="SYM-027"],[data-symptom="SYM-028"]').count(),0);await context.close();});
 await run('physical1202 check remains separate from frozen hardware outcome',async()=>{const {page,context}=await fresh();await search(page,'1202');await page.getByRole('button',{name:'There is debris or a physical blockage',exact:true}).click();await solve(page);assert.match(await page.locator('#result').innerText(),/Power off the mower/);await page.getByRole('button',{name:'Change symptom',exact:true}).click();await identify(page);await page.getByRole('button',{name:'Both cutting discs are free, but the error remains',exact:true}).click();await solve(page);await pie(page);await context.close();});
 await run('wrong scope and negative qualifier cannot reveal software repair',async()=>{const {page,context}=await fresh();await symptom(page,'SYM-004');await identify(page);await solve(page);await page.getByRole('heading',{name:'Confirm the mower details',exact:true}).waitFor();assert.equal(await page.locator('#result .answer-grid').count(),0);await page.locator('#edit-issue').click();await scope(page);await page.getByRole('button',{name:'No / unsure — contact PIE',exact:true}).click();await solve(page);await pie(page);await context.close();});
 await run('returned real repair persists after model changes and canonical reentry',async()=>{const {page,context}=await fresh();await scope(page);await symptom(page,'SYM-004');await page.getByRole('button',{name:'Yes, this matches',exact:true}).click();await solve(page);await page.getByRole('button',{name:'The issue returned after repair',exact:true}).click();await pie(page);assert.match(await page.locator('#result').innerText(),/issue returned after repair/i);await page.locator('#edit-issue').click();await page.locator('#model').selectOption('__other__');await scope(page);await search(page,'Cutting disc does not spin in Functional Test');await solve(page);await pie(page);await context.close();});
 await run('1008 NFF guard and arbitrary text are safe on separate pages',async()=>{const {page,context}=await fresh();await search(page,'1008');await page.getByRole('button',{name:'The workshop cannot reproduce it',exact:true}).click();await identify(page);await solve(page);assert.match(await page.locator('#result').innerText(),/Do not replace the keypad board/);await search(page,'<img src=x onerror=alert(1)>');await solve(page);await pie(page);assert.equal(await page.locator('img').count(),0);await context.close();});
 await run('synthetic next repair remains on solution page and cannot repeat after Back/reentry',async()=>{const {page,context}=await fresh();const fixture=await(await page.request.get(base+'/knowledge.json')).json();const card=structuredClone(fixture.cards.find(c=>c.id==='sym-cutting-functional-test'));card.id='fixture-repair';card.code='999001';card.message='Synthetic replacement contract';card.scope={status:'confirmed',models:['TEST MODEL'],firmware:['TEST VERSION']};const first={...card.paths[0],id:'cable',symptom:'First observed condition',part:'Fixture cable',action:['Replace fixture cable.'],qualifier:undefined,ifNotFixed:{kind:'path',pathId:'board',message:'Use the confirmed board step.'}};const second={...first,id:'board',directSelectable:false,part:'Fixture board',action:['Replace fixture board.'],ifNotFixed:{kind:'escalate',message:'Contact PIE. Do not repeat the replacement.'}};card.paths=[first,second];fixture.cards.push(card);await page.route('**/knowledge.json',r=>r.fulfill({json:fixture}));await page.reload();await page.locator('#search-button:enabled').waitFor();await page.locator('#model').selectOption('TEST MODEL');await page.locator('#firmware').fill('TEST VERSION');await search(page,'999001');await solve(page);await page.getByText('Fixture cable',{exact:true}).waitFor();await page.getByRole('button',{name:'Still not fixed',exact:true}).click();await page.getByText('Fixture board',{exact:true}).waitFor();await page.goBack();await identify(page);await solve(page);await page.getByText('Fixture board',{exact:true}).waitFor();await page.getByRole('button',{name:'Still not fixed',exact:true}).click();await pie(page);await search(page,'999001');await solve(page);await pie(page);await context.close();});
 for(const [name,reply] of [['unavailable',{status:503,body:'Unavailable'}],['invalid',{json:{schemaVersion:88,cards:[],symptoms:[]}}]])await run(name+' catalog disables both routes and direct solution access',async()=>{const {page,context}=await fresh();await page.route('**/knowledge.json',r=>r.fulfill(reply));await page.reload();await page.getByText('Guides could not load.',{exact:false}).waitFor();assert.equal(await page.locator('#search-button').isDisabled(),true);assert.equal(await page.locator('[data-area]').count(),0);assert.equal(await page.locator('#continue').count(),0);assert.equal(await page.locator('#result').innerText(),'');await context.close();});
 assert.deepEqual(errors,[]);assert.deepEqual(external,[]);
 fs.writeFileSync(path.join(root,'artifacts/two-page-verification.json'),JSON.stringify({passed:checks.length,checks,pageErrors:errors,externalRequests:external.length},null,2));
 fs.writeFileSync(path.join(root,'artifacts/browser-verification.json'),JSON.stringify({passed:checks.length,checks,viewports:['1366x768','1920x1080','390x844'],pageErrors:errors,externalRequests:external.length,twoPageSeparation:true,ownedServerClosedInFinally:true},null,2));
 console.log('TWO PAGE BROWSER GREEN '+checks.length);
}finally{await browser.close();await new Promise(r=>server.close(r));}
