import fs from 'node:fs';
import assert from 'node:assert/strict';
import {createRequire} from 'node:module';
import {build} from '../scripts/build.mjs';
import {createPreview} from '../scripts/serve.mjs';
import {enterSymptom,enterSearch,enterFirmware,choose,category,confirm,solve,identify,data} from './input-helpers.mjs';
const {chromium}=createRequire(import.meta.url)('C:/Users/Reggie/.cache/codex-runtimes/codex-primary-runtime/dependencies/node/node_modules/playwright');
await build();const server=await createPreview({port:0}),base='http://127.0.0.1:'+server.address().port;
const browser=await chromium.launch({headless:true,executablePath:'C:/Program Files (x86)/Microsoft/Edge/Application/msedge.exe'}),checks=[],errors=[],external=[];
const run=async(name,fn)=>{await fn();checks.push(name);console.log('PASS '+name);};
async function fresh(width=1366){const page=await browser.newPage({viewport:{width,height:width===1920?1080:width===390?844:768}});page.setDefaultTimeout(5000);page.on('pageerror',e=>errors.push(e.message));page.on('request',r=>{if(!r.url().startsWith(base)&&!r.url().startsWith('data:'))external.push(r.url());});await page.goto(base);await page.locator('#model:enabled').waitFor();return page;}
async function pie(page){await page.getByRole('heading',{name:'Next step with PIE',exact:true}).waitFor();assert.equal(await page.locator('#result .answer-grid').count(),0);}
async function noLeak(page){await identify(page);const text=await page.locator('#identify-page').textContent();assert.doesNotMatch(text,/Most likely faulty part|What to do|After repair|Upper Shell Adapter Cable|Cutting control software|REP-[A-Z]+|STABLE_OPERATIONAL_GUIDANCE/);}
async function software(page){await enterSymptom(page,'SYM-004','LUBA 2 5000X');await enterFirmware(page,'1.30.31.10');await confirm(page);}
try{
 for(const width of [1366,1920,390]){
  const page=await fresh(width);
  await run(width+' progressively separated identification and PIE-only symptom',async()=>{await noLeak(page);assert.equal(await page.locator('#symptom-stage').isVisible(),false);await enterSymptom(page,'SYM-008','LUBA 2');await noLeak(page);await solve(page);await pie(page);});
  await run(width+' exact1202 explicit condition and Back retain selections',async()=>{await enterSearch(page,'1202','SYM-004','LUBA 2');await page.getByRole('button',{name:'Both cutting discs are free, but the error remains',exact:true}).click();await noLeak(page);await solve(page);await pie(page);await page.goBack();assert.equal(await page.locator('#search').inputValue(),'1202');assert.equal(await page.locator('#observed-symptom').inputValue(),'SYM-004');await solve(page);await pie(page);});
  await run(width+' exact informational message does not dismiss selected fault',async()=>{await enterSearch(page,'Stereo self-calibration succeeded and the parameters were restored.','SYM-021','LUBA 2');await noLeak(page);await solve(page);await pie(page);assert.match(await page.locator('#result').innerText(),/successful self-calibration/);});
  await run(width+' fuzzy search only presents explicit candidates; unknown goes PIE',async()=>{await enterSearch(page,'port disconnected','SYM-021','LUBA 2');assert.equal(await page.locator('#continue').count(),0);await noLeak(page);await page.getByRole('button',{name:/1500.*Chassis data/}).click();await solve(page);await pie(page);await enterSearch(page,'999999','SYM-021','LUBA 2');await solve(page);await pie(page);});
  await run(width+' scoped software path keeps qualifier and verification gate',async()=>{await software(page);await noLeak(page);await solve(page);await page.getByText('Cutting control software',{exact:true}).waitFor();await page.getByRole('button',{name:'Fixed',exact:true}).click();assert.match(await page.locator('#status').innerText(),/checks.*first/);await page.locator('#verification').check();await page.getByRole('button',{name:'Fixed',exact:true}).click();await page.getByText('You reported it fixed',{exact:true}).waitFor();await page.screenshot({path:`artifacts/two-page-${width}-solution.png`,fullPage:true});});
  await run(width+' failure persists across symptom and auxiliary message reentry',async()=>{await software(page);await solve(page);await page.getByRole('button',{name:'Still not fixed',exact:true}).click();await pie(page);await enterSearch(page,'Cutting disc does not spin in Functional Test','SYM-004','LUBA 2 5000X');await solve(page);await pie(page);});
  await page.close();
 }
 await run('all25 controlled symptoms accessible for a supported model without Page1 leakage',async()=>{const page=await fresh();for(const s of data().symptoms){await enterSymptom(page,s.symptom_id);await noLeak(page);}assert.equal(data().symptoms.length,25);await page.close();});
 await run('ten areas retain explicit Other intake without repair inference',async()=>{const page=await fresh();for(const area of new Set(data().symptoms.map(s=>s.observable_area))){await category(page);await page.locator('#model').selectOption('LUBA 2');await page.locator('#observable-area').selectOption(area);await page.locator('#category-next').click();await page.locator('#observed-symptom').selectOption('__other__');await page.locator('#other-description').fill('1202 replace board now');await noLeak(page);await page.locator('#search-button').click();await solve(page);await pie(page);}await page.close();});
 await run('model edit invalidates forward result and clears firmware/symptom',async()=>{const page=await fresh();await software(page);await solve(page);await page.goBack();await category(page);await page.locator('#model').selectOption('LUBA 1');await page.goForward();await noLeak(page);assert.equal(await page.locator('#firmware').inputValue(),'');assert.equal(await page.locator('#observed-symptom').inputValue(),'');await page.close();});
 await run('code and symptom edits invalidate old result and require fresh resolution',async()=>{const page=await fresh();await enterSymptom(page,'SYM-007','LUBA 2');await solve(page);await page.goBack();if(await page.locator('#details-back').isVisible())await page.locator('#details-back').click();await page.locator('#search').fill('1202');await page.goForward();await noLeak(page);assert.equal(await page.locator('#continue').count(),0);await page.locator('#observed-symptom').selectOption('SYM-008');await page.locator('#search').fill('');await page.locator('#search-button').click();await solve(page);await pie(page);await page.close();});
 await run('refresh and direct URL cannot recover a repair or qualifier',async()=>{const page=await fresh();await software(page);await solve(page);for(const url of [base+'/?direct=1#solution',base+'/?direct=2#solution?model=LUBA%202&symptom=SYM-001']){await page.goto(url);await page.locator('#model:enabled').waitFor();await noLeak(page);assert.equal(await page.locator('#category-stage').isVisible(),true);assert.equal(await page.locator('#continue').count(),0);}await page.reload();await noLeak(page);await page.close();});
 await run('signed codes retain exact identity and historical firmware stays private',async()=>{const page=await fresh();for(const code of ['-2000303','2000303','1000022']){await enterSearch(page,code,'SYM-021','LUBA 2');await solve(page);await pie(page);assert.equal(await page.locator('#result article').getAttribute('data-card'),data().cards.find(c=>c.code===code).id);assert.doesNotMatch(await page.locator('#result').innerText(),/2\.3\.30\.26/);}await page.close();});
 await run('public projection and HTTP remain free of private candidate sources',async()=>{const page=await fresh();const payload=await(await page.request.get(base+'/knowledge.json')).text();assert.doesNotMatch(payload,/candidate_refs|REP-[A-Z0-9]+-\d{3}|evidence_state|repeated_use_signal/);for(const url of ['/data/feishu-candidates.json','/data/canonical.json','/lib/candidates.mjs'])assert.equal((await page.request.get(base+url)).status(),404);await page.close();});
 await run('1202 physical obstruction check remains available without frozen replacement',async()=>{const page=await fresh();await enterSearch(page,'1202','SYM-004','LUBA 2');await page.getByRole('button',{name:'There is debris or a physical blockage',exact:true}).click();await solve(page);assert.match(await page.locator('#result').innerText(),/Power off the mower/);assert.doesNotMatch(await page.locator('#result').innerText(),/Replace.*(?:cable|mainboard)/i);await page.getByRole('button',{name:'Still not fixed',exact:true}).click();await pie(page);await page.close();});
 await run('negative qualifier and incorrect firmware do not reveal scoped repair',async()=>{const page=await fresh();await enterSymptom(page,'SYM-004','LUBA 2 5000X');await enterFirmware(page,'0.0.0');await solve(page);assert.equal(await page.locator('#result .answer-grid').count(),0);await enterSymptom(page,'SYM-004','LUBA 2');await page.getByRole('button',{name:'No / unsure — contact PIE',exact:true}).click();await solve(page);await pie(page);await page.close();});
 await run('returned repair never restarts after controlled reentry',async()=>{const page=await fresh();await software(page);await solve(page);await page.getByRole('button',{name:'The issue returned after repair',exact:true}).click();await pie(page);await enterSymptom(page,'SYM-004','LUBA 2 5000X');await solve(page);await pie(page);await page.close();});
 await run('1008 controlled condition keeps cannot-reproduce guardrail',async()=>{const page=await fresh();await enterSearch(page,'1008','SYM-001','LUBA 2');await page.getByRole('button',{name:'The workshop cannot reproduce it',exact:true}).click();await noLeak(page);await solve(page);assert.match(await page.locator('#result').innerText(),/Do not replace the keypad board/);await page.close();});
 await run('arbitrary optional message cannot inject DOM or a repair',async()=>{const page=await fresh();await enterSearch(page,'<img src=x onerror=alert(1)>','SYM-021','LUBA 2');await solve(page);await pie(page);assert.equal(await page.locator('img').count(),0);await page.close();});
 for(const [name,reply] of [['unavailable',{status:503,body:'Unavailable'}],['invalid',{json:{schemaVersion:88,cards:[],symptoms:[]}}]])await run(name+' catalog keeps all controls disabled',async()=>{const page=await fresh();await page.route('**/knowledge.json',r=>r.fulfill(reply));await page.reload();await page.getByText('Guides could not load.',{exact:false}).waitFor();assert.equal(await page.locator('#model').isDisabled(),true);assert.equal(await page.locator('#observed-symptom').isDisabled(),true);assert.equal(await page.locator('#continue').count(),0);await noLeak(page);await page.close();});
 assert.deepEqual(errors,[]);assert.deepEqual(external,[]);const report={passed:checks.length,checks,viewports:['1366x768','1920x1080','390x844'],pageErrors:errors,externalRequests:0,twoPageSeparation:true};for(const name of ['browser-verification.json','two-page-verification.json'])fs.writeFileSync('artifacts/'+name,JSON.stringify(report,null,2));console.log('TWO PAGE BROWSER GREEN '+checks.length);
}finally{await browser.close();await new Promise(r=>server.close(r));}
